# Generated by Django 3.1.3 on 2020-11-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
