# Generated by Django 3.1.3 on 2020-11-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='last_name',
        ),
        migrations.AddField(
            model_name='receiver',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='receivers',
                                    to='orders.order'),
            preserve_default=False,
        ),
    ]
