# Generated by Django 3.1.3 on 2020-11-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_delivered',
            new_name='is_closed',
        ),
    ]
