# Generated by Django 3.1.3 on 2020-11-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='changes_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_last_changed',
        ),
    ]
