# Generated by Django 3.1.3 on 2020-11-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201118_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
    ]
