# Generated by Django 3.1.2 on 2020-11-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='is_subcategory',
        ),
    ]
