# Generated by Django 3.1.3 on 2020-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201112_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_last_changed',
            field=models.DateField(auto_now=True),
        ),
    ]
