# Generated by Django 3.1.3 on 2020-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_date_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_last_changed',
            field=models.DateField(default=0),
        ),
    ]
