# Generated by Django 3.1.3 on 2020-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201112_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_last_changed',
            field=models.DateField(),
        ),
    ]
