# Generated by Django 3.1.3 on 2020-11-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201112_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_last_changed',
            field=models.DateField(auto_now=True),
        ),
    ]
